# Generated by Django 2.1.7 on 2020-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Cpf', models.CharField(max_length=12)),
                ('Idade', models.IntegerField()),
                ('Data_de_Nascimento', models.DateField()),
                ('Telefone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=60)),
            ],
        ),
    ]
